version: "{build}"

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: "Visual Studio 15 2017"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      CMAKE_GENERATOR: "Visual Studio 12 2013"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"

configuration: Release

cache:
  - libs\src -> CMakeLists.txt

build_script:
  - cmake -G "%CMAKE_GENERATOR%" .
  # download static dependencies before actual build, with 3 chances to deal with network issues
  - msbuild download_static_deps.vcxproj /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" ||
    msbuild download_static_deps.vcxproj /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" ||
    msbuild download_static_deps.vcxproj /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild ALL_BUILD.vcxproj            /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild PACKAGE.vcxproj              /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild source_archive.vcxproj       /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild source_archive_fat.vcxproj   /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  # package and publish chocolatey package for the 32-bit build
  - ps: >
      if ($env:CMAKE_GENERATOR -eq "Visual Studio 12 2013") {
        msbuild package_choco.vcxproj      /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
      }

test_script:
  - msbuild RUN_TESTS.vcxproj            /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
  - path: bin/*.zip
